---
language: minimal
os: linux

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  jobs:
    - LISP=sbcl-bin
    - LISP=abcl-bin
    - LISP=ccl-bin
    - LISP=ecl
    - LISP=clisp

jobs:
  fast_finish: true
  allow_failures:
    - env: LISP=clisp

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  - ./bin/travis-roswell-setup.sh

before_script:
  - bin/fetch-configlet
  - bin/configlet lint .

script:
  - ros run -l 'src/xlisp-test/xlisp-test.lisp' -e '(xlisp-test:travis-build)' -q

# Cut and paste above to run all tests locally.

# Add a numeric argument to XLISP-TEST:RUN-TESTS-ALL between 0 and 7
# to control optional verbosity (default is 3).
